import { tv } from 'tailwind-variants';
import { LabelSize } from './label.enums';

export const labelVariants = tv({
  base: 'inline-flex select-none items-center gap-3xs font-sans text-neutral-600',
  variants: {
    // Maps onto the `.label-1/2/3` typography utilities generated by plugins.js, largest first.
    size: {
      lg: 'label-1',
      md: 'label-2',
      sm: 'label-3',
    },
    disabled: {
      true: 'opacity-40',
      false: '',
    },
  },
  defaultVariants: {
    size: LabelSize.Md,
    disabled: false,
  },
});
